apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docling-test-poc
  namespace: docling-test-poc
spec:
  ingressClassName: traefik
  rules:
  - host: docling.apps.rancher-poc.ad.curia.europa.eu
    http:
      paths:
      - backend:
          service:
            name: docling-serve-test-poc
            port:
              number: 5001
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - docling-poc.apps.rancher-poc.ad.curia.europa.eu
    secretName: wildcard-docling-poc
