apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docling-artifacts
  namespace: docling-test-poc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvm-local
  resources:
    requests:
      storage: 50Gi
